### ISSUE TITLE
steam apparmor profile unable to enforce

### ISSUE THREAD

**Issue by ka223** [mk-fg/apparmor-profiles#2]
I use lubuntu 14.04 64Bit and I can not use this profile.

any hints?

thanks 

```
sudo aa-enforce /etc/apparmor.d/usr.bin.steam 
Traceback (most recent call last):
  File "/usr/sbin/aa-enforce", line 30, in <module>
    tool.cmd_enforce()
  File "/usr/lib/python3/dist-packages/apparmor/tools.py", line 139, in cmd_enforce
    apparmor.read_profiles()
  File "/usr/lib/python3/dist-packages/apparmor/aa.py", line 2594, in read_profiles
    read_profile(profile_dir + '/' + file, True)
  File "/usr/lib/python3/dist-packages/apparmor/aa.py", line 2620, in read_profile
    profile_data = parse_profile_data(data, file, 0)
  File "/usr/lib/python3/dist-packages/apparmor/aa.py", line 2961, in parse_profile_data
    load_include(include_name)
  File "/usr/lib/python3/dist-packages/apparmor/aa.py", line 4464, in load_include
    raise AppArmorException("Include file %s not found" % (profile_dir + '/' + incfile) )
apparmor.common.AppArmorException: 'Include file /etc/apparmor.d/abstractions/site/base not found'
$ sudo rm usr.bin.steam 
$ sudo aa-enforce /etc/apparmor.d/*
Profile for /etc/apparmor.d/abstractions not found, skipping
Profile for /etc/apparmor.d/apache2.d not found, skipping
Setting /etc/apparmor.d/bin.ping to enforce mode.
Profile for /etc/apparmor.d/cache not found, skipping
Profile for /etc/apparmor.d/disable not found, skipping
Profile for /etc/apparmor.d/force-complain not found, skipping
Setting /etc/apparmor.d/lightdm-guest-session to enforce mode.
Profile for /etc/apparmor.d/local not found, skipping
Profile for /etc/apparmor.d/program-chunks not found, skipping
Setting /etc/apparmor.d/sbin.dhclient to enforce mode.
Setting /etc/apparmor.d/sbin.klogd to enforce mode.
Setting /etc/apparmor.d/sbin.syslogd to enforce mode.
Setting /etc/apparmor.d/sbin.syslog-ng to enforce mode.
Profile for /etc/apparmor.d/tunables not found, skipping
Setting /etc/apparmor.d/usr.bin.chromium-browser to enforce mode.
Setting /etc/apparmor.d/usr.bin.evince to enforce mode.
Setting /etc/apparmor.d/usr.bin.firefox to enforce mode.
Profile for /etc/apparmor.d/usr.bin.firefox.dpkg-old not found, skipping
Setting /etc/apparmor.d/usr.lib.dovecot.deliver to enforce mode.
Setting /etc/apparmor.d/usr.lib.dovecot.dovecot-auth to enforce mode.
Setting /etc/apparmor.d/usr.lib.dovecot.imap to enforce mode.
Setting /etc/apparmor.d/usr.lib.dovecot.imap-login to enforce mode.
Setting /etc/apparmor.d/usr.lib.dovecot.managesieve-login to enforce mode.
Setting /etc/apparmor.d/usr.lib.dovecot.pop3 to enforce mode.
Setting /etc/apparmor.d/usr.lib.dovecot.pop3-login to enforce mode.
Setting /etc/apparmor.d/usr.sbin.avahi-daemon to enforce mode.
Setting /etc/apparmor.d/usr.sbin.cupsd to enforce mode.
Setting /etc/apparmor.d/usr.sbin.dnsmasq to enforce mode.
Setting /etc/apparmor.d/usr.sbin.dovecot to enforce mode.
Setting /etc/apparmor.d/usr.sbin.identd to enforce mode.
Setting /etc/apparmor.d/usr.sbin.mdnsd to enforce mode.
Setting /etc/apparmor.d/usr.sbin.nmbd to enforce mode.
Setting /etc/apparmor.d/usr.sbin.nscd to enforce mode.
Setting /etc/apparmor.d/usr.sbin.ntpd to enforce mode.
Setting /etc/apparmor.d/usr.sbin.rsyslogd to enforce mode.
Setting /etc/apparmor.d/usr.sbin.smbd to enforce mode.
Setting /etc/apparmor.d/usr.sbin.tcpdump to enforce mode.
Setting /etc/apparmor.d/usr.sbin.traceroute to enforce mode.
$ dpkg -l | grep apparmor
ii  apparmor                              2.8.95~2430-0ubuntu5.2                  amd64        User-space parser utility for AppArmor
ii  apparmor-profiles                     2.8.95~2430-0ubuntu5.2                  all          Profiles for AppArmor Security policies
ii  apparmor-utils                        2.8.95~2430-0ubuntu5.2                  amd64        Utilities for controlling AppArmor
ii  libapparmor-perl                      2.8.95~2430-0ubuntu5.2                  amd64        AppArmor library Perl bindings
ii  libapparmor1:amd64                    2.8.95~2430-0ubuntu5.2                  amd64        changehat AppArmor library
ii  python3-apparmor                      2.8.95~2430-0ubuntu5.2                  amd64        AppArmor Python3 utility library
ii  python3-libapparmor                   2.8.95~2430-0ubuntu5.2                  amd64        AppArmor library Python3 bindings
```

**Comment by mk-fg** [comment]
When you ran aa-enforce, it gave you this error message:

    apparmor.common.AppArmorException: 'Include file /etc/apparmor.d/abstractions/site/base not found'

(from the stuff you pasted above)

Isn't that enough of a hint? Tells exactly what the problem is in a clear language, it seems.

**Comment by mk-fg** [comment]
Please check the README file btw for details on what's in the `site/*` files.
Also note that I don't expect these profiles to work on any linux distro (these are just profiles I wrote for myself), as should also be clearly stated there.

**Comment by ka223** [comment]
Sure, I saw that, but the site folder is also not there.
Which linux are you using?

**Comment by mk-fg** [comment]
"site" folder is right there in `profiles/abstractions/site`: https://github.com/mk-fg/apparmor-profiles/tree/master/profiles/abstractions/site
I.e. if you replace `/etc/apparmor.d` in that error message with `profiles` from the repo, it should be there.

Currently I'm using Arch on this desktop, but wrote most of these when using Exherbo.
